// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/exemple.tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/ArticleExemple.tsx";
import * as $$1 from "./islands/Articles.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/Footer.tsx";
import * as $$4 from "./islands/Header.tsx";
import * as $$5 from "./islands/Navbar.tsx";
import * as $$6 from "./islands/ProjectIsland.tsx";
import * as $$7 from "./islands/Projects.tsx";
import * as $$8 from "./islands/Services.tsx";
import * as $$9 from "./islands/Technologies.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/exemple.tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/ArticleExemple.tsx": $$0,
    "./islands/Articles.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/Footer.tsx": $$3,
    "./islands/Header.tsx": $$4,
    "./islands/Navbar.tsx": $$5,
    "./islands/ProjectIsland.tsx": $$6,
    "./islands/Projects.tsx": $$7,
    "./islands/Services.tsx": $$8,
    "./islands/Technologies.tsx": $$9,
  },
  baseUrl: import.meta.url,
};

export default manifest;
